#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ -x /bin/btrfs ]
then
	copy_exec /bin/btrfs /bin
	if [ ! -x /usr/share/initramfs-tools/hooks/fsck ] && [ ! -x /etc/initramfs-tools/hooks/fsck ]
	then
	    copy_exec /sbin/fsck.btrfs /sbin
	fi

	# Copy udev rules, which udev no longer does
	for UDEV_RULE in 64-btrfs.rules 64-btrfs-dm.rules; do
	  for rules_folder in /lib/udev/rules.d /etc/udev/rules.d; do
	    if [ -f $rules_folder/$UDEV_RULE ]; then
	      mkdir -p $DESTDIR$rules_folder
	      cp $rules_folder/$UDEV_RULE $DESTDIR$rules_folder/$UDEV_RULE
	    fi
	  done
	done
fi
